import pandas as pd, numpy as np
pd.set_option('display.width',260); pd.set_option('display.max_columns',60); pd.set_option('display.max_rows',200)
t=pd.read_csv('data/raw/tickets.csv',dtype=str,keep_default_na=False)
o=pd.read_csv('data/raw/orders.csv',dtype=str,keep_default_na=False)
pr=pd.read_csv('data/raw/products.csv',dtype=str,keep_default_na=False)
a=pd.read_csv('data/raw/agents.csv',dtype=str,keep_default_na=False)
t['amt']=pd.to_numeric(t.refund_amount_inr.replace('',np.nan),errors='coerce')
t['amt_norm']=np.where(t.source_system=='legacy_fd',t.amt/100,t.amt)
t['pref']=t.source_system.map({'helpdesk':0,'legacy_fd':1})
c=t.sort_values('pref').drop_duplicates('ticket_id',keep='first').copy()
c['cdate']=pd.to_datetime(c.created_at); c['m']=c.cdate.dt.to_period('M')
c['rdate']=pd.to_datetime(c.resolved_at.replace('',np.nan)); c['rm']=c.rdate.dt.to_period('M')
cr=c[c.amt_norm.notna()].copy()
print("canonical rows:",len(c)," refund rows:",len(cr)," total:",cr.amt_norm.sum())

print("\n=== month basis: created vs resolved (refund rows) ===")
diff=(cr.m!=cr.rm)&cr.rm.notna()
print("refund rows where created-month != resolved-month:",diff.sum(),"of",len(cr))
print("refund rows with no resolved_at:",cr.rm.isna().sum())

print("\n=== MONTHLY (created-month) ===")
mm=cr.groupby('m').agg(amt=('amt_norm','sum'),n=('ticket_id','size'))
mm['all_tickets']=c.groupby('m').size()
mm['refund_rate%']=(mm.n/mm.all_tickets*100).round(1)
print(mm.to_string())

print("\n=== outliers vs order value / retail ===")
o2=o.rename(columns={'sku':'o_sku'})
j=cr.merge(o2[['order_id','order_value_inr','qty','o_sku','order_date']],on='order_id',how='left')
j['ov']=pd.to_numeric(j.order_value_inr,errors='coerce')
pr2=pr.copy(); pr2['rp']=pd.to_numeric(pr2.retail_price_inr); pr2['uc']=pd.to_numeric(pr2.unit_cost_inr)
j=j.merge(pr2[['sku','rp','uc','product_name']],left_on='product_sku',right_on='sku',how='left')
has=j.ov.notna()
print("refund rows with order joined:",has.sum())
print("refund > order_value:",((j.amt_norm>j.ov)&has).sum(), " amount:",j[(j.amt_norm>j.ov)&has].amt_norm.sum())
print("refund > 1.5x order_value:",((j.amt_norm>1.5*j.ov)&has).sum())
print("refund > retail_price:",(j.amt_norm>j.rp).sum())
print("\nexamples refund>order_value:\n",j[(j.amt_norm>j.ov)&has][['ticket_id','product_sku','amt_norm','ov','qty','refund_reason_code','assigned_team']].head(10).to_string())
print("\nrefund/order_value ratio distribution:\n",(j[has].amt_norm/j[has].ov).describe([.05,.25,.5,.75,.95,.99]).to_string())

print("\n=== AGENT view ===")
ag=cr.groupby('agent_id').agg(ref_amt=('amt_norm','sum'),ref_n=('ticket_id','size'))
ag['tickets']=c.groupby('agent_id').size()
ag=ag.join(a.set_index('agent_id')[['name','team','tier','site','shift']])
ag['ref_rate%']=(ag.ref_n/ag.tickets*100).round(1)
ag['avg_ref']=(ag.ref_amt/ag.ref_n).round(0)
gw=cr[cr.refund_reason_code=='GW-OTHER'].groupby('agent_id').agg(gw_n=('ticket_id','size'),gw_amt=('amt_norm','sum'))
ag=ag.join(gw).fillna({'gw_n':0,'gw_amt':0})
ag['gw_share%']=(ag.gw_amt/ag.ref_amt*100).round(1)
print(ag.sort_values('ref_amt',ascending=False)[['name','team','tier','tickets','ref_n','ref_rate%','ref_amt','avg_ref','gw_n','gw_amt','gw_share%']].to_string())

print("\n=== TEAM view ===")
tm=cr.groupby('assigned_team').agg(ref_amt=('amt_norm','sum'),ref_n=('ticket_id','size'))
tm['tickets']=c.groupby('assigned_team').size(); tm['rate%']=(tm.ref_n/tm.tickets*100).round(1)
print(tm.sort_values('ref_amt',ascending=False).to_string())
