import pandas as pd, numpy as np
pd.set_option('display.width',260)
t=pd.read_csv('data/raw/tickets.csv',dtype=str,keep_default_na=False)
print("transfers by source:\n",pd.crosstab(t.source_system,t.transfers))
print("\ncsat blank by source:\n",pd.crosstab(t.source_system,t.csat_score==''))
print("\ncsat values:",sorted(t.csat_score.unique()))
t['amt']=pd.to_numeric(t.refund_amount_inr.replace('',np.nan),errors='coerce')
t['amt_norm']=np.where(t.source_system=='legacy_fd',t.amt/100,t.amt)
t['pref']=t.source_system.map({'helpdesk':0,'legacy_fd':1})
c=t.sort_values('pref').drop_duplicates('ticket_id',keep='first').copy()
cr=c[c.amt_norm.notna()]
print("\nrefunds on open/pending:",cr[cr.status.isin(['open','pending'])].shape[0],"amt:",cr[cr.status.isin(['open','pending'])].amt_norm.sum())
print("\nnon-integer rupee amounts:",(cr.amt_norm%1!=0).sum())
print("min/max canonical:",cr.amt_norm.min(),cr.amt_norm.max())
print("\nzero amounts:",(cr.amt_norm==0).sum())
print("\ncategory vs reason_code top:\n",pd.crosstab(cr.category,cr.refund_reason_code).to_string())
print("\ncanonical ticket_id coverage: distinct",c.ticket_id.nunique(),"rows",len(c))
print("\nticket_id numeric range:",c.ticket_id.str.extract(r'(\d+)')[0].astype(int).agg(['min','max']).to_dict())
print("gaps in ticket_id sequence:", (c.ticket_id.str.extract(r'(\d+)')[0].astype(int).max()-c.ticket_id.str.extract(r'(\d+)')[0].astype(int).min()+1)-c.ticket_id.nunique())
